apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: 
spec:
  api:
    loadBalancer:
      class: Network
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  containerRuntime: containerd
  configBase: s3://
  dnsZone: 
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-eu-north-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-eu-north-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-eu-north-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-eu-north-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-eu-north-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-eu-north-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://
  enableAWSOIDCProvider: true
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 172
  kubernetesVersion: 1.31.7
  networkCIDR: 
  networkID: vpc-
  networking:
  nonMasqueradeCIDR: 10.10.0.0/16
  sshAccess:
  - 172
  subnets:
  - cidr: 
    id: subnet-
    name: eu-north-1a
    type: Private
    zone: eu-north-1a
    egress: nat-
  - cidr: 
    id: subnet-
    name: eu-north-1b
    type: Private
    zone: eu-north-1b
    egress: nat-
  - cidr: 
    id: subnet-
    name: eu-north-1c
    type: Private
    zone: eu-north-1c
    egress: nat-
  - cidr:
    id: subnet-
    name: utility-eu-north-1a
    type: Utility
    zone: eu-north-1a
  - cidr: 
    id: subnet-
    name: utility-eu-north-1b
    type: Utility
    zone: eu-north-1b
  - cidr: 
    id: subnet-
    name: utility-eu-north-1c
    type: Utility
    zone: eu-north-1c
  topology:
    dns:
      type: Private
  certManager:
    enabled: true
  metricsServer:
    enabled: true
    insecure: false
  clusterAutoscaler:
    enabled: true
    expander: least-waste
    awsUseStaticInstanceList: false
    scaleDownDelayAfterAdd: 10m0s
    scaleDownUnneededTime: 5m0s
    scaleDownUnreadyTime: 10m0s
  nodeTerminationHandler:
    enabled: true
    enableSQSTerminationDraining: true
    managedASGTag: "aws-node-termination-handler/managed"


---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.k8s.
  name: control-plane-eu-north-1a
spec:
  image: ami-0c1ac8a41498c1a9c
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-north-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.k8s.
  name: control-plane-eu-north-1b
spec:
  image: ami-0c1ac8a41498c1a9c
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-north-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.k8s.
  name: control-plane-eu-north-1c
spec:
  image: ami-0c1ac8a41498c1a9c
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-north-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.k8s.
  name: nodes-eu-north-1a
spec:
  instanceMetadata:
    httpTokens: optional
  image: ami-0c1ac8a41498c1a9c
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - eu-north-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.k8s.
  name: nodes-eu-north-1b
spec:
  instanceMetadata:
    httpTokens: optional
  image: ami-0c1ac8a41498c1a9c
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - eu-north-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.k8s.
  name: nodes-eu-north-1c
spec:
  instanceMetadata:
    httpTokens: optional
  image: ami-0c1ac8a41498c1a9c
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - eu-north-1c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.k8s.your-domain.net
  name: spot-nodes-eu-north-1
spec:
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: optional
  image: ami-0c1ac8a41498c1a9c
  mixedInstancesPolicy:
    instanceRequirements:
      cpu:
        min: "2"
        max: "16"
      memory:
        min: "2G"
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  min: 0
  max: 3
  role: Node
  subnets:
  - eu-north-1a
  - eu-north-1b
  - eu-north-1c

