# This is a basic workflow to help you get started with Actions

name: CD_Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: ["terraform/*/*"]

  workflow_dispatch:
#
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        working-directory: ./terraform 
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secret.AWS_SECRET_KEY_ID }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform plan
        id: TerraformPlan
        run: | 
          terraform init
          terraform plan -var='example_api_key=${{ secrets.EXAMPLE_API_KEY }}'
   
